const path = require('node:path');
const { mkdirSync, writeFileSync } = require('node:fs');
const { BrowserWindow, ipcMain, session } = require('electron');

const YOUTUBE_PARTITION = 'persist:youtube-login';
const LOGIN_URL =
  'https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F';
const PRELOAD_PATH = path.join(__dirname, 'youtube-preload.cjs');

let loginWindow = null;
let activeSaveHandler = null;

function isRelevantCookie(cookie) {
  const domain = (cookie.domain ?? '').toLowerCase();
  return (
    domain.includes('youtube.com') ||
    domain.includes('youtu.be') ||
    domain.includes('google.com')
  );
}

function formatDomain(domain) {
  const trimmed = domain.trim();
  if (!trimmed) return trimmed;
  return trimmed.startsWith('.') ? trimmed : `.${trimmed}`;
}

function sanitizeCookieValue(value) {
  return String(value ?? '')
    .replace(/[\t\r\n]/g, '')
    .trim();
}

function toNetscapeExpiration(cookie) {
  if (typeof cookie.expirationDate === 'number' && cookie.expirationDate > 0) {
    return Math.floor(cookie.expirationDate);
  }
  return Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365;
}

async function exportYoutubeCookies(destPath) {
  mkdirSync(path.dirname(destPath), { recursive: true });

  const youtubeSession = session.fromPartition(YOUTUBE_PARTITION);
  const cookies = await youtubeSession.cookies.get({});
  const relevant = cookies.filter(isRelevantCookie);

  if (relevant.length === 0) {
    throw new Error('No YouTube/Google cookies were found. Finish signing in and try again.');
  }

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by Stream Media Board',
    '',
  ];

  for (const cookie of relevant) {
    const domain = formatDomain(cookie.domain ?? '');
    const name = sanitizeCookieValue(cookie.name);
    const value = sanitizeCookieValue(cookie.value);
    if (!domain || !name || !value) continue;

    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const cookiePath = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = String(toNetscapeExpiration(cookie));
    lines.push([domain, includeSubdomains, cookiePath, secure, expires, name, value].join('\t'));
  }

  if (lines.length <= 3) {
    throw new Error('Could not export any usable YouTube cookies.');
  }

  writeFileSync(destPath, `${lines.join('\n')}\n`, 'utf8');
  return { cookieCount: lines.length - 3, destPath };
}

async function hasExportableCookies() {
  const youtubeSession = session.fromPartition(YOUTUBE_PARTITION);
  const cookies = await youtubeSession.cookies.get({});
  return cookies.filter(isRelevantCookie).length > 0;
}

function closeLoginWindowWithoutPrompt() {
  if (!loginWindow || loginWindow.isDestroyed()) {
    loginWindow = null;
    return;
  }
  loginWindow._closingWithoutPrompt = true;
  loginWindow.close();
}

async function saveYoutubeSession(cookiesFile, onSaved) {
  const result = await exportYoutubeCookies(cookiesFile);
  onSaved?.(result);
  closeLoginWindowWithoutPrompt();
  return result;
}

function registerYoutubeAuthIpc(cookiesFile, onSaved) {
  if (activeSaveHandler) {
    ipcMain.removeHandler('youtube-auth:save');
  }

  activeSaveHandler = async () => {
    try {
      return await saveYoutubeSession(cookiesFile, onSaved);
    } catch (err) {
      const { dialog } = require('electron');
      dialog.showErrorBox(
        'YouTube sign-in',
        err instanceof Error ? err.message : String(err),
      );
      throw err;
    }
  };

  ipcMain.handle('youtube-auth:save', activeSaveHandler);
}

function openYoutubeLoginWindow({ cookiesFile, onSaved }) {
  registerYoutubeAuthIpc(cookiesFile, onSaved);

  if (loginWindow && !loginWindow.isDestroyed()) {
    loginWindow.focus();
    return loginWindow;
  }

  loginWindow = new BrowserWindow({
    width: 980,
    height: 760,
    autoHideMenuBar: true,
    title: 'Sign in to YouTube',
    webPreferences: {
      partition: YOUTUBE_PARTITION,
      contextIsolation: true,
      nodeIntegration: false,
      preload: PRELOAD_PATH,
    },
  });

  loginWindow.on('close', (event) => {
    if (!loginWindow || loginWindow.isDestroyed()) return;
    if (loginWindow._closingWithoutPrompt) return;

    event.preventDefault();
    void (async () => {
      const { dialog } = require('electron');
      try {
        const hasCookies = await hasExportableCookies();
        if (!hasCookies) {
          closeLoginWindowWithoutPrompt();
          return;
        }

        const answer = dialog.showMessageBoxSync(loginWindow, {
          type: 'question',
          title: 'YouTube sign-in',
          message: 'Save this YouTube session for audio downloads?',
          detail:
            'You signed in successfully. Save the session now so the app can download YouTube audio.',
          buttons: ['Save session', 'Close without saving', 'Cancel'],
          defaultId: 0,
          cancelId: 2,
        });

        if (answer === 2) return;

        if (answer === 0) {
          await saveYoutubeSession(cookiesFile, onSaved);
          return;
        }

        closeLoginWindowWithoutPrompt();
      } catch (err) {
        dialog.showErrorBox(
          'YouTube sign-in',
          err instanceof Error ? err.message : String(err),
        );
      }
    })();
  });

  loginWindow.on('closed', () => {
    loginWindow = null;
  });

  loginWindow.webContents.on('did-finish-load', () => {
    if (!loginWindow || loginWindow.isDestroyed()) return;
    loginWindow.webContents
      .executeJavaScript(
        `
          (() => {
            if (document.getElementById('psp-youtube-login-bar')) return;
            const bar = document.createElement('div');
            bar.id = 'psp-youtube-login-bar';
            bar.style.cssText = 'position:fixed;top:0;left:0;right:0;z-index:2147483647;background:#0f172a;color:#e2e8f0;padding:12px 16px;display:flex;align-items:center;justify-content:space-between;gap:12px;font:14px Segoe UI,sans-serif;box-shadow:0 2px 12px rgba(0,0,0,.35)';
            bar.innerHTML = '<span>Sign in with your Google account, then click <strong>Save session</strong>.</span>';
            const btn = document.createElement('button');
            btn.textContent = 'Save session';
            btn.style.cssText = 'background:#38bdf8;color:#0f172a;border:0;border-radius:6px;padding:8px 14px;font-weight:600;cursor:pointer';
            btn.addEventListener('click', async () => {
              btn.disabled = true;
              btn.textContent = 'Saving...';
              try {
                await window.pspYoutubeAuth.saveSession();
              } catch (err) {
                btn.disabled = false;
                btn.textContent = 'Save session';
                alert(err && err.message ? err.message : 'Could not save the YouTube session.');
              }
            });
            bar.appendChild(btn);
            document.body.prepend(bar);
          })();
        `,
        true,
      )
      .catch(() => {
        /* noop */
      });
  });

  void loginWindow.loadURL(LOGIN_URL);
  return loginWindow;
}

function getYoutubeCookiesPath(appDataDir) {
  return path.join(appDataDir, 'youtube.cookies.txt');
}

module.exports = {
  exportYoutubeCookies,
  getYoutubeCookiesPath,
  openYoutubeLoginWindow,
};
